dynamodb:
  name: dynamodb-local
  image:
    repository: amazon/dynamodb-local
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

orderApi:
  name: order-api
  image:
    repository: order-api
    tag: latest
    pullPolicy: IfNotPresent
  tag: latest
  pullPolicy: IfNotPresent
  ports:
    containerPort: 8000
  service:
    type: NodePort
    port: 8000
    nodePort: 31000
  orderProcessorUrl: http://order-processor:8000

orderProcessor:
  name: order-processor
  image:
    repository: order-processor
    tag: latest
    pullPolicy: IfNotPresent
  pullPolicy: IfNotPresent
  ports:
    containerPort: 8000
  service:
    type: ClusterIP
    port: 8000
