apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.orderApi.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.orderApi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.orderApi.name }}
    spec:
      containers:
        - name: {{ .Values.orderApi.name }}
          image: "{{ .Values.orderApi.image.repository }}:{{ .Values.orderApi.image.tag }}"
          imagePullPolicy: "{{ .Values.orderApi.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.orderApi.ports.containerPort }}
          env:
            - name: DYNAMODB_ENDPOINT
              value: "http://dynamodb-local:8000"
            - name: AWS_ACCESS_KEY_ID
              value: "local"
            - name: AWS_SECRET_ACCESS_KEY
              value: "local"
            - name: AWS_DEFAULT_REGION
              value: "us-west-2"
            - name: ORDER_PROCESSOR_URL
              value: "{{ .Values.orderApi.orderProcessorUrl }}"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.orderApi.ports.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 30
          